#!/usr/bin/env python3
"""
__APP_NAME__ — WebSkill Actions
Auto-generated by WebSkill Generator. Re-run generator.py --update to refresh.

Usage:
  python3 actions.py --list
  python3 actions.py --action "COMMAND_NAME"
  python3 actions.py --action "COMMAND_NAME" --params '{"key": "value"}'
  python3 actions.py --interactive
"""

import argparse
import json
import time
from pathlib import Path
from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout

SKILL_DIR = Path(__file__).parent
CONFIG_PATH = SKILL_DIR / "config.json"
APP_NAME = "__APP_NAME__"

COMMANDS = __COMMANDS_JSON__


def _load_config():
    with open(CONFIG_PATH) as f:
        return json.load(f)

def _wait(page, ms=8000):
    try: page.wait_for_load_state("networkidle", timeout=ms)
    except: pass
    time.sleep(0.4)

def _authenticate(page, ctx, cfg):
    auth_method = cfg.get("auth_method", "none")
    if auth_method == "form":
        username = cfg.get("username", "")
        password = cfg.get("password", "")
        page.goto(cfg["url"], timeout=20000)
        _wait(page)
        for sel in ['input[type="email"]', 'input[name="email"]', 'input[name="username"]', 'input[id*="user"]']:
            try:
                el = page.locator(sel).first
                if el.is_visible(timeout=2000):
                    el.fill(username); break
            except: continue
        for sel in ['input[type="password"]', 'input[name="password"]']:
            try:
                el = page.locator(sel).first
                if el.is_visible(timeout=2000):
                    el.fill(password); break
            except: continue
        for sel in ['button[type="submit"]', 'button:has-text("Login")', 'button:has-text("Sign in")', 'button:has-text("Log in")']:
            try:
                el = page.locator(sel).first
                if el.is_visible(timeout=2000):
                    el.click(); _wait(page, 12000); break
            except: continue
    elif auth_method == "apikey":
        api_key = cfg.get("api_key", "")
        header_name = cfg.get("api_key_header", "Authorization")
        page.route("**/*", lambda route, req: route.continue_(headers={**req.headers, header_name: api_key}))
        page.goto(cfg["url"], timeout=20000); _wait(page)
    elif auth_method == "cookie":
        ctx.add_cookies(cfg.get("cookies", []))
        page.goto(cfg["url"], timeout=20000); _wait(page)
    else:
        page.goto(cfg["url"], timeout=20000); _wait(page)

def _goto_page(page, url, cfg):
    if page.url != url:
        page.goto(url, timeout=20000); _wait(page)

def _execute_click(page, cfg, command, params):
    _goto_page(page, command["page"], cfg)
    label = command.get("command", "")
    selector = command.get("selector", "")
    for sel in [selector, 'button:has-text("' + label + '")', '[aria-label="' + label + '"]']:
        if not sel: continue
        try:
            el = page.locator(sel).first
            if el.is_visible(timeout=3000):
                el.click(); _wait(page)
                return {"status": "ok", "url": page.url, "title": page.title()}
        except: continue
    return {"status": "error", "message": "Could not find button: " + label}

def _execute_form_fill(page, cfg, command, params):
    _goto_page(page, command["page"], cfg)
    fields = command.get("fields", [])
    submit_label = command.get("submit_label", "submit")
    for field_name in fields:
        value = params.get(field_name, "")
        if not value: continue
        for sel in ['input[name="' + field_name + '"]', 'input[id="' + field_name + '"]',
                    'input[placeholder*="' + field_name + '"]', 'textarea[name="' + field_name + '"]']:
            try:
                el = page.locator(sel).first
                if el.is_visible(timeout=2000):
                    el.fill(str(value)); break
            except: continue
    for sel in ['button:has-text("' + submit_label + '")', 'button[type="submit"]', 'input[type="submit"]']:
        try:
            el = page.locator(sel).first
            if el.is_visible(timeout=2000):
                el.click(); _wait(page)
                return {"status": "ok", "url": page.url}
        except: continue
    return {"status": "error", "message": "Could not submit form"}

def _execute_api(page, cfg, command, params):
    import urllib.request
    url = command["url"]
    method = command.get("method", "GET")
    headers = {}
    if cfg.get("auth_method") == "apikey":
        headers[cfg.get("api_key_header", "Authorization")] = cfg.get("api_key", "")
    try:
        data = json.dumps(params).encode() if params and method != "GET" else None
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        with urllib.request.urlopen(req, timeout=15) as resp:
            body = resp.read().decode()
            try: return {"status": "ok", "data": json.loads(body)}
            except: return {"status": "ok", "raw": body[:2000]}
    except Exception as e:
        return {"status": "error", "message": str(e)}

def execute_command(page, ctx, cfg, command_name, params=None):
    params = params or {}
    cmd = next((c for c in COMMANDS if c["command"].lower() == command_name.lower()), None)
    if not cmd:
        matches = [c for c in COMMANDS if command_name.lower() in c["command"].lower()]
        cmd = matches[0] if matches else None
    if not cmd:
        return {"status": "error", "message": "Command not found: " + command_name + ". Use --list to see commands."}
    atype = cmd.get("action_type", "click")
    if atype == "click": return _execute_click(page, cfg, cmd, params)
    elif atype == "form_fill": return _execute_form_fill(page, cfg, cmd, params)
    elif atype == "api": return _execute_api(page, cfg, cmd, params)
    else: return {"status": "error", "message": "Unknown action type: " + atype}

def list_commands():
    sep = "─" * 60
    print("\n" + sep + "\n  " + APP_NAME + " — Available Commands\n" + sep)
    for i, cmd in enumerate(COMMANDS, 1):
        print("  {:2d}. [{:10s}] {}".format(i, cmd.get("action_type", "?"), cmd["command"]))
        print("        " + cmd.get("description", ""))
    print(sep + "\n")

def interactive_mode(page, ctx, cfg):
    print("\n🤖 " + APP_NAME + " — Interactive Mode\nType a command (or 'list' / 'quit')\n")
    while True:
        try: user_input = input("Command> ").strip()
        except (EOFError, KeyboardInterrupt): break
        if not user_input or user_input.lower() in ("q", "quit", "exit"): break
        if user_input.lower() in ("list", "ls", "help", "?"): list_commands(); continue
        params = {}
        if "{" in user_input:
            try:
                idx = user_input.index("{")
                params = json.loads(user_input[idx:])
                user_input = user_input[:idx].strip()
            except: pass
        print(json.dumps(execute_command(page, ctx, cfg, user_input, params), indent=2))

def main():
    parser = argparse.ArgumentParser(description=APP_NAME + " WebSkill Actions")
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--action")
    parser.add_argument("--params", default="{}")
    parser.add_argument("--interactive", "-i", action="store_true")
    parser.add_argument("--headful", action="store_true")
    args = parser.parse_args()
    cfg = _load_config()
    if args.list:
        list_commands(); return
    with sync_playwright() as pw:
        browser = pw.chromium.launch(headless=not args.headful)
        ctx = browser.new_context(viewport={"width": 1280, "height": 900})
        page = ctx.new_page()
        try:
            _authenticate(page, ctx, cfg)
            if args.interactive: interactive_mode(page, ctx, cfg)
            elif args.action:
                try: params = json.loads(args.params)
                except: params = {}
                print(json.dumps(execute_command(page, ctx, cfg, args.action, params), indent=2))
            else: parser.print_help()
        finally: browser.close()

if __name__ == "__main__":
    main()
